# Generated by Django 4.2.7 on 2023-11-11 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0005_gallery_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery_images',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='gallery_images',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
