# Generated by Django 4.2.7 on 2023-11-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0007_alter_gallery_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagespost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='postapp.post'),
        ),
    ]
